import mongoose from "mongoose";

/**
 * Signal model for tracking academic integrity, SLA breaches, and system escalations.
 * Signals are actionable alerts generated by automated auditors or manual supervisors.
 */
const signalSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      enum: ["integrity", "sla", "performance", "governance"],
      required: true,
    },
    category: {
      type: String,
      required: true, 
      // Examples: plagiarism, authorship_anomaly, evaluation_delay, milestone_miss
    },
    severity: {
      type: String,
      enum: ["low", "medium", "high", "critical"],
      default: "low",
    },
    status: {
      type: String,
      enum: ["open", "investigating", "resolved", "dismissed"],
      default: "open",
    },
    message: {
      type: String,
      required: true,
    },
    project: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Project",
    },
    group: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Group",
    },
    triggeredBy: {
      type: String,
      enum: ["system_auditor", "supervisor", "admin"],
      default: "system_auditor",
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed,
    },
    resolvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    resolvedAt: Date,
    resolutionNote: String,
  },
  { timestamps: true },
);

signalSchema.index({ type: 1, status: 1 });
signalSchema.index({ project: 1 });
signalSchema.index({ group: 1 });

const Signal = mongoose.model("Signal", signalSchema);

export default Signal;
